//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Strings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your full street address, apartment, city, and zip code....
        /// </summary>
        internal static string Account_AddressPlaceholder {
            get {
                return ResourceManager.GetString("Account_AddressPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back to Homepage.
        /// </summary>
        internal static string Account_BackHome {
            get {
                return ResourceManager.GetString("Account_BackHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string Account_Cancel {
            get {
                return ResourceManager.GetString("Account_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Password.
        /// </summary>
        internal static string Account_ChangePasswordBtn {
            get {
                return ResourceManager.GetString("Account_ChangePasswordBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm New Password.
        /// </summary>
        internal static string Account_ConfirmPassword {
            get {
                return ResourceManager.GetString("Account_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current Password.
        /// </summary>
        internal static string Account_CurrentPassword {
            get {
                return ResourceManager.GetString("Account_CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Default Delivery Location.
        /// </summary>
        internal static string Account_DefaultLocation {
            get {
                return ResourceManager.GetString("Account_DefaultLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email Address.
        /// </summary>
        internal static string Account_EmailAddress {
            get {
                return ResourceManager.GetString("Account_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The email cannot be modified..
        /// </summary>
        internal static string Account_EmailWarning {
            get {
                return ResourceManager.GetString("Account_EmailWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First Name.
        /// </summary>
        internal static string Account_FirstName {
            get {
                return ResourceManager.GetString("Account_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot your password?.
        /// </summary>
        internal static string Account_ForgotPassword {
            get {
                return ResourceManager.GetString("Account_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last Name.
        /// </summary>
        internal static string Account_LastName {
            get {
                return ResourceManager.GetString("Account_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My Account.
        /// </summary>
        internal static string Account_MainTitle {
            get {
                return ResourceManager.GetString("Account_MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Drag the pin to your exact home location..
        /// </summary>
        internal static string Account_MapInstructions {
            get {
                return ResourceManager.GetString("Account_MapInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Password.
        /// </summary>
        internal static string Account_NewPassword {
            get {
                return ResourceManager.GetString("Account_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string Account_PasswordLabel {
            get {
                return ResourceManager.GetString("Account_PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personal Information.
        /// </summary>
        internal static string Account_PersonalInfo {
            get {
                return ResourceManager.GetString("Account_PersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone Number.
        /// </summary>
        internal static string Account_PhoneNumber {
            get {
                return ResourceManager.GetString("Account_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save Changes.
        /// </summary>
        internal static string Account_SaveChanges {
            get {
                return ResourceManager.GetString("Account_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Security &amp; Password.
        /// </summary>
        internal static string Account_SecurityTitle {
            get {
                return ResourceManager.GetString("Account_SecurityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shipping Address.
        /// </summary>
        internal static string Account_ShippingAddress {
            get {
                return ResourceManager.GetString("Account_ShippingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update Password.
        /// </summary>
        internal static string Account_UpdatePasswordBtn {
            get {
                return ResourceManager.GetString("Account_UpdatePasswordBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        internal static string Account_Username {
            get {
                return ResourceManager.GetString("Account_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back to Login.
        /// </summary>
        internal static string Auth_BackLogin {
            get {
                return ResourceManager.GetString("Auth_BackLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Password.
        /// </summary>
        internal static string Auth_BtnChangePass {
            get {
                return ResourceManager.GetString("Auth_BtnChangePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Complete Registration.
        /// </summary>
        internal static string Auth_BtnCompleteReg {
            get {
                return ResourceManager.GetString("Auth_BtnCompleteReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log in.
        /// </summary>
        internal static string Auth_BtnLogin {
            get {
                return ResourceManager.GetString("Auth_BtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recovery.
        /// </summary>
        internal static string Auth_BtnRecover {
            get {
                return ResourceManager.GetString("Auth_BtnRecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create account.
        /// </summary>
        internal static string Auth_BtnSignUp {
            get {
                return ResourceManager.GetString("Auth_BtnSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verify Token.
        /// </summary>
        internal static string Auth_BtnVerify {
            get {
                return ResourceManager.GetString("Auth_BtnVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your new password.
        /// </summary>
        internal static string Auth_ChangePassSub {
            get {
                return ResourceManager.GetString("Auth_ChangePassSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CHANGE PASSWORD.
        /// </summary>
        internal static string Auth_ChangePassTitle {
            get {
                return ResourceManager.GetString("Auth_ChangePassTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm Password *.
        /// </summary>
        internal static string Auth_ConfirmPass {
            get {
                return ResourceManager.GetString("Auth_ConfirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm Password *.
        /// </summary>
        internal static string Auth_ConfirmPassInput {
            get {
                return ResourceManager.GetString("Auth_ConfirmPassInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use a different email.
        /// </summary>
        internal static string Auth_DiffEmail {
            get {
                return ResourceManager.GetString("Auth_DiffEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email *.
        /// </summary>
        internal static string Auth_Email {
            get {
                return ResourceManager.GetString("Auth_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First Name *.
        /// </summary>
        internal static string Auth_FirstName {
            get {
                return ResourceManager.GetString("Auth_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot your password?.
        /// </summary>
        internal static string Auth_ForgotPass {
            get {
                return ResourceManager.GetString("Auth_ForgotPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continue with Google.
        /// </summary>
        internal static string Auth_GoogleLogin {
            get {
                return ResourceManager.GetString("Auth_GoogleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign up with Google.
        /// </summary>
        internal static string Auth_GoogleSignUp {
            get {
                return ResourceManager.GetString("Auth_GoogleSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Already have an account?.
        /// </summary>
        internal static string Auth_HaveAccount {
            get {
                return ResourceManager.GetString("Auth_HaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last Name *.
        /// </summary>
        internal static string Auth_LastName {
            get {
                return ResourceManager.GetString("Auth_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log in.
        /// </summary>
        internal static string Auth_LinkLogin {
            get {
                return ResourceManager.GetString("Auth_LinkLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign up.
        /// </summary>
        internal static string Auth_LinkSignUp {
            get {
                return ResourceManager.GetString("Auth_LinkSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome back! Please enter your details..
        /// </summary>
        internal static string Auth_LoginSub {
            get {
                return ResourceManager.GetString("Auth_LoginSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log in.
        /// </summary>
        internal static string Auth_LoginTitle {
            get {
                return ResourceManager.GetString("Auth_LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Password *.
        /// </summary>
        internal static string Auth_NewPassInput {
            get {
                return ResourceManager.GetString("Auth_NewPassInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do not have an account?.
        /// </summary>
        internal static string Auth_NoAccount {
            get {
                return ResourceManager.GetString("Auth_NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password *.
        /// </summary>
        internal static string Auth_Password {
            get {
                return ResourceManager.GetString("Auth_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username or Email *.
        /// </summary>
        internal static string Auth_RecoverInput {
            get {
                return ResourceManager.GetString("Auth_RecoverInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No problem. Enter your username or email and we&apos;ll help you recover it..
        /// </summary>
        internal static string Auth_RecoverSub {
            get {
                return ResourceManager.GetString("Auth_RecoverSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RECOVER.
        /// </summary>
        internal static string Auth_RecoverTitle {
            get {
                return ResourceManager.GetString("Auth_RecoverTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Already remembered?.
        /// </summary>
        internal static string Auth_Remembered {
            get {
                return ResourceManager.GetString("Auth_Remembered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buy the best football shirts of all time..
        /// </summary>
        internal static string Auth_SignUpSub {
            get {
                return ResourceManager.GetString("Auth_SignUpSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create an account.
        /// </summary>
        internal static string Auth_SignUpTitle {
            get {
                return ResourceManager.GetString("Auth_SignUpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verification Token *.
        /// </summary>
        internal static string Auth_TokenInput {
            get {
                return ResourceManager.GetString("Auth_TokenInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the code sent to your email.
        /// </summary>
        internal static string Auth_TokenSub {
            get {
                return ResourceManager.GetString("Auth_TokenSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VERIFY TOKEN.
        /// </summary>
        internal static string Auth_TokenTitle {
            get {
                return ResourceManager.GetString("Auth_TokenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User or Email *.
        /// </summary>
        internal static string Auth_UserEmail {
            get {
                return ResourceManager.GetString("Auth_UserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username *.
        /// </summary>
        internal static string Auth_Username {
            get {
                return ResourceManager.GetString("Auth_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please confirm your password..
        /// </summary>
        internal static string Auth_ValConfirmPass {
            get {
                return ResourceManager.GetString("Auth_ValConfirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter your new password..
        /// </summary>
        internal static string Auth_ValNewPass {
            get {
                return ResourceManager.GetString("Auth_ValNewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter your password..
        /// </summary>
        internal static string Auth_ValPass {
            get {
                return ResourceManager.GetString("Auth_ValPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter your token..
        /// </summary>
        internal static string Auth_ValToken {
            get {
                return ResourceManager.GetString("Auth_ValToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your user..
        /// </summary>
        internal static string Auth_ValUser {
            get {
                return ResourceManager.GetString("Auth_ValUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We&apos;ve sent a 6-digit code to.
        /// </summary>
        internal static string Auth_VerifyEmailSub1 {
            get {
                return ResourceManager.GetString("Auth_VerifyEmailSub1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please check your inbox (and spam folder) and enter the code below to activate your account..
        /// </summary>
        internal static string Auth_VerifyEmailSub2 {
            get {
                return ResourceManager.GetString("Auth_VerifyEmailSub2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verify Email.
        /// </summary>
        internal static string Auth_VerifyEmailTitle {
            get {
                return ResourceManager.GetString("Auth_VerifyEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BEST SELLER.
        /// </summary>
        internal static string Card_BestSeller {
            get {
                return ResourceManager.GetString("Card_BestSeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buy.
        /// </summary>
        internal static string Card_BuyBtn {
            get {
                return ResourceManager.GetString("Card_BuyBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NEW.
        /// </summary>
        internal static string Card_New {
            get {
                return ResourceManager.GetString("Card_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PRINT.
        /// </summary>
        internal static string Card_Print {
            get {
                return ResourceManager.GetString("Card_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SALE.
        /// </summary>
        internal static string Card_Sale {
            get {
                return ResourceManager.GetString("Card_Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shop Now.
        /// </summary>
        internal static string Card_ShopNow {
            get {
                return ResourceManager.GetString("Card_ShopNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sizes:.
        /// </summary>
        internal static string Card_Sizes {
            get {
                return ResourceManager.GetString("Card_Sizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View Details.
        /// </summary>
        internal static string Card_ViewDetails {
            get {
                return ResourceManager.GetString("Card_ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proceed to Checkout.
        /// </summary>
        internal static string Cart_BtnCheckout {
            get {
                return ResourceManager.GetString("Cart_BtnCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continue Shopping.
        /// </summary>
        internal static string Cart_BtnContinue {
            get {
                return ResourceManager.GetString("Cart_BtnContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove.
        /// </summary>
        internal static string Cart_BtnRemove {
            get {
                return ResourceManager.GetString("Cart_BtnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Image.
        /// </summary>
        internal static string Cart_HeaderImage {
            get {
                return ResourceManager.GetString("Cart_HeaderImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unitary Price.
        /// </summary>
        internal static string Cart_HeaderPrice {
            get {
                return ResourceManager.GetString("Cart_HeaderPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quantity.
        /// </summary>
        internal static string Cart_HeaderQuantity {
            get {
                return ResourceManager.GetString("Cart_HeaderQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Size.
        /// </summary>
        internal static string Cart_HeaderSize {
            get {
                return ResourceManager.GetString("Cart_HeaderSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subtotal.
        /// </summary>
        internal static string Cart_HeaderSubtotal {
            get {
                return ResourceManager.GetString("Cart_HeaderSubtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a T-Shirt.
        /// </summary>
        internal static string Cart_HeaderTShirt {
            get {
                return ResourceManager.GetString("Cart_HeaderTShirt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your Shopping Cart.
        /// </summary>
        internal static string Cart_MainTitle {
            get {
                return ResourceManager.GetString("Cart_MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total to pay:.
        /// </summary>
        internal static string Cart_TotalToPay {
            get {
                return ResourceManager.GetString("Cart_TotalToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address.
        /// </summary>
        internal static string Checkout_Address {
            get {
                return ResourceManager.GetString("Checkout_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apply.
        /// </summary>
        internal static string Checkout_ApplyCoupon {
            get {
                return ResourceManager.GetString("Checkout_ApplyCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Billing address.
        /// </summary>
        internal static string Checkout_BillingTitle {
            get {
                return ResourceManager.GetString("Checkout_BillingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm Delivery Location.
        /// </summary>
        internal static string Checkout_ConfirmLocation {
            get {
                return ResourceManager.GetString("Checkout_ConfirmLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Department.
        /// </summary>
        internal static string Checkout_Department {
            get {
                return ResourceManager.GetString("Checkout_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Discount Applied.
        /// </summary>
        internal static string Checkout_DiscountApplied {
            get {
                return ResourceManager.GetString("Checkout_DiscountApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a District / Town.
        /// </summary>
        internal static string Checkout_District {
            get {
                return ResourceManager.GetString("Checkout_District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        internal static string Checkout_Email {
            get {
                return ResourceManager.GetString("Checkout_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First Name.
        /// </summary>
        internal static string Checkout_FirstName {
            get {
                return ResourceManager.GetString("Checkout_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Have a coupon code?.
        /// </summary>
        internal static string Checkout_HaveCoupon {
            get {
                return ResourceManager.GetString("Checkout_HaveCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PRODUCT.
        /// </summary>
        internal static string Checkout_HeaderProduct {
            get {
                return ResourceManager.GetString("Checkout_HeaderProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TOTAL.
        /// </summary>
        internal static string Checkout_HeaderTotal {
            get {
                return ResourceManager.GetString("Checkout_HeaderTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last Name.
        /// </summary>
        internal static string Checkout_LastName {
            get {
                return ResourceManager.GetString("Checkout_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loading interactive map....
        /// </summary>
        internal static string Checkout_LoadingMap {
            get {
                return ResourceManager.GetString("Checkout_LoadingMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Click the map or drag the pin to confirm the exact delivery location..
        /// </summary>
        internal static string Checkout_MapInstructions {
            get {
                return ResourceManager.GetString("Checkout_MapInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Municipality.
        /// </summary>
        internal static string Checkout_Municipality {
            get {
                return ResourceManager.GetString("Checkout_Municipality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Order Notes (Optional).
        /// </summary>
        internal static string Checkout_OrderNotes {
            get {
                return ResourceManager.GetString("Checkout_OrderNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cash on Delivery.
        /// </summary>
        internal static string Checkout_PayCash {
            get {
                return ResourceManager.GetString("Checkout_PayCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pay with cash upon delivery at your doorstep. Please try to have the exact amount ready..
        /// </summary>
        internal static string Checkout_PayCashDesc {
            get {
                return ResourceManager.GetString("Checkout_PayCashDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paypal System.
        /// </summary>
        internal static string Checkout_PayPaypal {
            get {
                return ResourceManager.GetString("Checkout_PayPaypal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pay safely via PayPal using your credit card, debit card, or PayPal balance. You will be redirected to the secure gateway to complete your transaction..
        /// </summary>
        internal static string Checkout_PayPaypalDesc {
            get {
                return ResourceManager.GetString("Checkout_PayPaypalDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Virtual Wallet.
        /// </summary>
        internal static string Checkout_PayWallet {
            get {
                return ResourceManager.GetString("Checkout_PayWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use your Virtual Wallet account to pay safely..
        /// </summary>
        internal static string Checkout_PayWalletDesc {
            get {
                return ResourceManager.GetString("Checkout_PayWalletDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Place Order.
        /// </summary>
        internal static string Checkout_PlaceOrder {
            get {
                return ResourceManager.GetString("Checkout_PlaceOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search an address or place....
        /// </summary>
        internal static string Checkout_SearchMapPlaceholder {
            get {
                return ResourceManager.GetString("Checkout_SearchMapPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shipping.
        /// </summary>
        internal static string Checkout_Shipping {
            get {
                return ResourceManager.GetString("Checkout_Shipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I&apos;ve read and accept the .
        /// </summary>
        internal static string Checkout_TermsText1 {
            get {
                return ResourceManager.GetString("Checkout_TermsText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a terms &amp; conditions.
        /// </summary>
        internal static string Checkout_TermsText2 {
            get {
                return ResourceManager.GetString("Checkout_TermsText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your Order.
        /// </summary>
        internal static string Checkout_YourOrderTitle {
            get {
                return ResourceManager.GetString("Checkout_YourOrderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back to Homepage.
        /// </summary>
        internal static string Contact_BackHome {
            get {
                return ResourceManager.GetString("Contact_BackHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Condition (1-10 Scale).
        /// </summary>
        internal static string Contact_Condition {
            get {
                return ResourceManager.GetString("Contact_Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consignment Details.
        /// </summary>
        internal static string Contact_ConsignTitle {
            get {
                return ResourceManager.GetString("Contact_ConsignTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter the details of your request. A member of our support staff will respond as soon as possible..
        /// </summary>
        internal static string Contact_DetailsPlaceholder {
            get {
                return ResourceManager.GetString("Contact_DetailsPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description / Details.
        /// </summary>
        internal static string Contact_DetailsTitle {
            get {
                return ResourceManager.GetString("Contact_DetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your email address.
        /// </summary>
        internal static string Contact_EmailLabel {
            get {
                return ResourceManager.GetString("Contact_EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please log in to auto-fill your email.
        /// </summary>
        internal static string Contact_EmailPlaceholder {
            get {
                return ResourceManager.GetString("Contact_EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please select your issue below to show the relevant fields..
        /// </summary>
        internal static string Contact_HelpDesc {
            get {
                return ResourceManager.GetString("Contact_HelpDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a What do you need help with?.
        /// </summary>
        internal static string Contact_HelpWith {
            get {
                return ResourceManager.GetString("Contact_HelpWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Order ID.
        /// </summary>
        internal static string Contact_OrderId {
            get {
                return ResourceManager.GetString("Contact_OrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can find this in your confirmation email or My Orders section..
        /// </summary>
        internal static string Contact_OrderIdDesc {
            get {
                return ResourceManager.GetString("Contact_OrderIdDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a e.g., 34.
        /// </summary>
        internal static string Contact_OrderIdPlaceholder {
            get {
                return ResourceManager.GetString("Contact_OrderIdPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proposed Price ($).
        /// </summary>
        internal static string Contact_Price {
            get {
                return ResourceManager.GetString("Contact_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jersey Size.
        /// </summary>
        internal static string Contact_Size {
            get {
                return ResourceManager.GetString("Contact_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subject.
        /// </summary>
        internal static string Contact_Subject {
            get {
                return ResourceManager.GetString("Contact_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Submit Request.
        /// </summary>
        internal static string Contact_SubmitBtn {
            get {
                return ResourceManager.GetString("Contact_SubmitBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Submit a request.
        /// </summary>
        internal static string Contact_Title {
            get {
                return ResourceManager.GetString("Contact_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a or click anywhere in this box to browse files.
        /// </summary>
        internal static string Contact_UploadClick {
            get {
                return ResourceManager.GetString("Contact_UploadClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Max. 3 images allowed. Supported formats: JPG, PNG, WEBP. Max. file size: 2MB..
        /// </summary>
        internal static string Contact_UploadDesc {
            get {
                return ResourceManager.GetString("Contact_UploadDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Drag &amp; Drop your images here.
        /// </summary>
        internal static string Contact_UploadDrag {
            get {
                return ResourceManager.GetString("Contact_UploadDrag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Upload Proof Images (Front, Back, Product Tags).
        /// </summary>
        internal static string Contact_UploadTitle {
            get {
                return ResourceManager.GetString("Contact_UploadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add to Cart.
        /// </summary>
        internal static string Detail_AddToCart {
            get {
                return ResourceManager.GetString("Detail_AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name (Max. 12 letters).
        /// </summary>
        internal static string Detail_CustomName {
            get {
                return ResourceManager.GetString("Detail_CustomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number.
        /// </summary>
        internal static string Detail_CustomNumber {
            get {
                return ResourceManager.GetString("Detail_CustomNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get your favorite name and number printed for just.
        /// </summary>
        internal static string Detail_CustomPriceInfo {
            get {
                return ResourceManager.GetString("Detail_CustomPriceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to customize your T-shirt?.
        /// </summary>
        internal static string Detail_CustomPrompt {
            get {
                return ResourceManager.GetString("Detail_CustomPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Only uppercase alphanumeric characters are allowed..
        /// </summary>
        internal static string Detail_CustomWarning {
            get {
                return ResourceManager.GetString("Detail_CustomWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Quantity:.
        /// </summary>
        internal static string Detail_SelectQuantity {
            get {
                return ResourceManager.GetString("Detail_SelectQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Size:.
        /// </summary>
        internal static string Detail_SelectSize {
            get {
                return ResourceManager.GetString("Detail_SelectSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Size Guide.
        /// </summary>
        internal static string Detail_SizeGuide {
            get {
                return ResourceManager.GetString("Detail_SizeGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Team:.
        /// </summary>
        internal static string Detail_Team {
            get {
                return ResourceManager.GetString("Detail_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Year:.
        /// </summary>
        internal static string Detail_Year {
            get {
                return ResourceManager.GetString("Detail_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Measurements are shown in centimeters (cm). These are standard fan-version measurements. Please allow a slight variance due to manufacturing..
        /// </summary>
        internal static string Modal_SizeGuideDesc {
            get {
                return ResourceManager.GetString("Modal_SizeGuideDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chest (cm).
        /// </summary>
        internal static string Modal_TableHeaderChest {
            get {
                return ResourceManager.GetString("Modal_TableHeaderChest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Length (cm).
        /// </summary>
        internal static string Modal_TableHeaderLength {
            get {
                return ResourceManager.GetString("Modal_TableHeaderLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Size.
        /// </summary>
        internal static string Modal_TableHeaderSize {
            get {
                return ResourceManager.GetString("Modal_TableHeaderSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DATE PURCHASED:.
        /// </summary>
        internal static string MyOrders_DatePurchased {
            get {
                return ResourceManager.GetString("MyOrders_DatePurchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You haven&apos;t placed any orders yet!.
        /// </summary>
        internal static string MyOrders_NoOrders {
            get {
                return ResourceManager.GetString("MyOrders_NoOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Order Reference.
        /// </summary>
        internal static string MyOrders_OrderRef {
            get {
                return ResourceManager.GetString("MyOrders_OrderRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Products Ordered.
        /// </summary>
        internal static string MyOrders_ProductsOrdered {
            get {
                return ResourceManager.GetString("MyOrders_ProductsOrdered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SHIPPING DETAILS:.
        /// </summary>
        internal static string MyOrders_ShippingDetails {
            get {
                return ResourceManager.GetString("MyOrders_ShippingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status.
        /// </summary>
        internal static string MyOrders_Status {
            get {
                return ResourceManager.GetString("MyOrders_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Review the details and status of all your purchases in OFFSIDESHOP.
        /// </summary>
        internal static string MyOrders_SubTitle {
            get {
                return ResourceManager.GetString("MyOrders_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My Order History.
        /// </summary>
        internal static string MyOrders_Title {
            get {
                return ResourceManager.GetString("MyOrders_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Charged.
        /// </summary>
        internal static string MyOrders_TotalCharged {
            get {
                return ResourceManager.GetString("MyOrders_TotalCharged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View Details &amp; Actions.
        /// </summary>
        internal static string MyOrders_ViewDetails {
            get {
                return ResourceManager.GetString("MyOrders_ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrator.
        /// </summary>
        internal static string Nav_AdminRole {
            get {
                return ResourceManager.GetString("Nav_AdminRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back to Shop.
        /// </summary>
        internal static string Nav_BackToShop {
            get {
                return ResourceManager.GetString("Nav_BackToShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dashboard.
        /// </summary>
        internal static string Nav_Dashboard {
            get {
                return ResourceManager.GetString("Nav_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log in.
        /// </summary>
        internal static string Nav_Login {
            get {
                return ResourceManager.GetString("Nav_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log out.
        /// </summary>
        internal static string Nav_LogOut {
            get {
                return ResourceManager.GetString("Nav_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My Account.
        /// </summary>
        internal static string Nav_MyAccount {
            get {
                return ResourceManager.GetString("Nav_MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My Orders.
        /// </summary>
        internal static string Nav_MyOrders {
            get {
                return ResourceManager.GetString("Nav_MyOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign up.
        /// </summary>
        internal static string Nav_SignUp {
            get {
                return ResourceManager.GetString("Nav_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address:.
        /// </summary>
        internal static string OrderDetail_Address {
            get {
                return ResourceManager.GetString("OrderDetail_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back to My Orders.
        /// </summary>
        internal static string OrderDetail_BackToOrders {
            get {
                return ResourceManager.GetString("OrderDetail_BackToOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel Order.
        /// </summary>
        internal static string OrderDetail_CancelOrder {
            get {
                return ResourceManager.GetString("OrderDetail_CancelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connecting to delivery driver....
        /// </summary>
        internal static string OrderDetail_ConnectingDriver {
            get {
                return ResourceManager.GetString("OrderDetail_ConnectingDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Customer:.
        /// </summary>
        internal static string OrderDetail_Customer {
            get {
                return ResourceManager.GetString("OrderDetail_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Items in your Order.
        /// </summary>
        internal static string OrderDetail_ItemsInOrder {
            get {
                return ResourceManager.GetString("OrderDetail_ItemsInOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Items Subtotal:.
        /// </summary>
        internal static string OrderDetail_ItemsSubtotal {
            get {
                return ResourceManager.GetString("OrderDetail_ItemsSubtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Live Tracking.
        /// </summary>
        internal static string OrderDetail_LiveTracking {
            get {
                return ResourceManager.GetString("OrderDetail_LiveTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loading order status....
        /// </summary>
        internal static string OrderDetail_LoadingStatus {
            get {
                return ResourceManager.GetString("OrderDetail_LoadingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Method:.
        /// </summary>
        internal static string OrderDetail_Method {
            get {
                return ResourceManager.GetString("OrderDetail_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Additional Comments (Optional):.
        /// </summary>
        internal static string OrderDetail_ModalComments {
            get {
                return ResourceManager.GetString("OrderDetail_ModalComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provide more details here... (Required if &apos;Other&apos; is selected).
        /// </summary>
        internal static string OrderDetail_ModalCommentsPlaceholder {
            get {
                return ResourceManager.GetString("OrderDetail_ModalCommentsPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Go Back.
        /// </summary>
        internal static string OrderDetail_ModalGoBack {
            get {
                return ResourceManager.GetString("OrderDetail_ModalGoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please select a reason from the list and explain why you want to proceed with this request..
        /// </summary>
        internal static string OrderDetail_ModalReasonDesc {
            get {
                return ResourceManager.GetString("OrderDetail_ModalReasonDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provide a Reason for.
        /// </summary>
        internal static string OrderDetail_ModalReasonTitle {
            get {
                return ResourceManager.GetString("OrderDetail_ModalReasonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a Reason:.
        /// </summary>
        internal static string OrderDetail_ModalSelectReason {
            get {
                return ResourceManager.GetString("OrderDetail_ModalSelectReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No notes provided..
        /// </summary>
        internal static string OrderDetail_NoNotes {
            get {
                return ResourceManager.GetString("OrderDetail_NoNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Order Notes:.
        /// </summary>
        internal static string OrderDetail_OrderNotes {
            get {
                return ResourceManager.GetString("OrderDetail_OrderNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payment Information.
        /// </summary>
        internal static string OrderDetail_PaymentTitle {
            get {
                return ResourceManager.GetString("OrderDetail_PaymentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone:.
        /// </summary>
        internal static string OrderDetail_Phone {
            get {
                return ResourceManager.GetString("OrderDetail_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Placed on:.
        /// </summary>
        internal static string OrderDetail_PlacedOn {
            get {
                return ResourceManager.GetString("OrderDetail_PlacedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Price.
        /// </summary>
        internal static string OrderDetail_Price {
            get {
                return ResourceManager.GetString("OrderDetail_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product Details.
        /// </summary>
        internal static string OrderDetail_ProductDetails {
            get {
                return ResourceManager.GetString("OrderDetail_ProductDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quantity.
        /// </summary>
        internal static string OrderDetail_Quantity {
            get {
                return ResourceManager.GetString("OrderDetail_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Request Refund.
        /// </summary>
        internal static string OrderDetail_RequestRefund {
            get {
                return ResourceManager.GetString("OrderDetail_RequestRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shipping Cost:.
        /// </summary>
        internal static string OrderDetail_ShippingCost {
            get {
                return ResourceManager.GetString("OrderDetail_ShippingCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shipping Address.
        /// </summary>
        internal static string OrderDetail_ShippingTitle {
            get {
                return ResourceManager.GetString("OrderDetail_ShippingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Size:.
        /// </summary>
        internal static string OrderDetail_Size {
            get {
                return ResourceManager.GetString("OrderDetail_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subtotal.
        /// </summary>
        internal static string OrderDetail_Subtotal {
            get {
                return ResourceManager.GetString("OrderDetail_Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Track Delivery.
        /// </summary>
        internal static string OrderDetail_TrackDelivery {
            get {
                return ResourceManager.GetString("OrderDetail_TrackDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transaction ID:.
        /// </summary>
        internal static string OrderDetail_TransactionId {
            get {
                return ResourceManager.GetString("OrderDetail_TransactionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Next.
        /// </summary>
        internal static string Pager_Next {
            get {
                return ResourceManager.GetString("Pager_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a of.
        /// </summary>
        internal static string Pager_Of {
            get {
                return ResourceManager.GetString("Pager_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Page.
        /// </summary>
        internal static string Pager_Page {
            get {
                return ResourceManager.GetString("Pager_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Previous.
        /// </summary>
        internal static string Pager_Prev {
            get {
                return ResourceManager.GetString("Pager_Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Try adjusting your filters or search keywords in the sidebar panel..
        /// </summary>
        internal static string Results_EmptySub {
            get {
                return ResourceManager.GetString("Results_EmptySub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No shirts matched your selected combination..
        /// </summary>
        internal static string Results_EmptyTitle {
            get {
                return ResourceManager.GetString("Results_EmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Products Found.
        /// </summary>
        internal static string Results_FoundCount {
            get {
                return ResourceManager.GetString("Results_FoundCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search Results View.
        /// </summary>
        internal static string Results_MainTitle {
            get {
                return ResourceManager.GetString("Results_MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your Comment.
        /// </summary>
        internal static string Review_CommentLabel {
            get {
                return ResourceManager.GetString("Review_CommentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Share your thoughts about this jersey....
        /// </summary>
        internal static string Review_CommentPlaceholder {
            get {
                return ResourceManager.GetString("Review_CommentPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        internal static string Review_DeleteBtn {
            get {
                return ResourceManager.GetString("Review_DeleteBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete this review?.
        /// </summary>
        internal static string Review_DeleteConfirm {
            get {
                return ResourceManager.GetString("Review_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leave a Review.
        /// </summary>
        internal static string Review_LeaveTitle {
            get {
                return ResourceManager.GetString("Review_LeaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must purchase this shirt before leaving a review..
        /// </summary>
        internal static string Review_MustPurchase {
            get {
                return ResourceManager.GetString("Review_MustPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are no reviews for this shirt.
        /// </summary>
        internal static string Review_NoReviews {
            get {
                return ResourceManager.GetString("Review_NoReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Official Reply.
        /// </summary>
        internal static string Review_OfficialReply {
            get {
                return ResourceManager.GetString("Review_OfficialReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rating.
        /// </summary>
        internal static string Review_Rating {
            get {
                return ResourceManager.GetString("Review_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reply.
        /// </summary>
        internal static string Review_ReplyBtn {
            get {
                return ResourceManager.GetString("Review_ReplyBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write an official reply....
        /// </summary>
        internal static string Review_ReplyPlaceholder {
            get {
                return ResourceManager.GetString("Review_ReplyPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Submit Review.
        /// </summary>
        internal static string Review_SubmitBtn {
            get {
                return ResourceManager.GetString("Review_SubmitBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Brand.
        /// </summary>
        internal static string Search_BrandLabel {
            get {
                return ResourceManager.GetString("Search_BrandLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        internal static string Search_Btn {
            get {
                return ResourceManager.GetString("Search_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Any Kit.
        /// </summary>
        internal static string Search_KitAny {
            get {
                return ResourceManager.GetString("Search_KitAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type of KIT.
        /// </summary>
        internal static string Search_KitLabel {
            get {
                return ResourceManager.GetString("Search_KitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        internal static string Search_Label {
            get {
                return ResourceManager.GetString("Search_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a League.
        /// </summary>
        internal static string Search_LeagueLabel {
            get {
                return ResourceManager.GetString("Search_LeagueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filters &amp; Search.
        /// </summary>
        internal static string Search_MobileBtn {
            get {
                return ResourceManager.GetString("Search_MobileBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search by team, brand, year....
        /// </summary>
        internal static string Search_Placeholder {
            get {
                return ResourceManager.GetString("Search_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Collections.
        /// </summary>
        internal static string Section_Collections {
            get {
                return ResourceManager.GetString("Section_Collections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leagues.
        /// </summary>
        internal static string Section_Leagues {
            get {
                return ResourceManager.GetString("Section_Leagues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Jerseys.
        /// </summary>
        internal static string Section_NewJerseys {
            get {
                return ResourceManager.GetString("Section_NewJerseys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a See more.
        /// </summary>
        internal static string Section_SeeMore {
            get {
                return ResourceManager.GetString("Section_SeeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Top Selling.
        /// </summary>
        internal static string Section_TopSelling {
            get {
                return ResourceManager.GetString("Section_TopSelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILTER BY.
        /// </summary>
        internal static string Sidebar_BtnFilter {
            get {
                return ResourceManager.GetString("Sidebar_BtnFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Competition / League.
        /// </summary>
        internal static string Sidebar_Competition {
            get {
                return ResourceManager.GetString("Sidebar_Competition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Price Range.
        /// </summary>
        internal static string Sidebar_Price {
            get {
                return ResourceManager.GetString("Sidebar_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All Prices.
        /// </summary>
        internal static string Sidebar_PriceAll {
            get {
                return ResourceManager.GetString("Sidebar_PriceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Over $150.
        /// </summary>
        internal static string Sidebar_PriceOver150 {
            get {
                return ResourceManager.GetString("Sidebar_PriceOver150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Under $50.
        /// </summary>
        internal static string Sidebar_PriceUnder50 {
            get {
                return ResourceManager.GetString("Sidebar_PriceUnder50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Supports Custom Print.
        /// </summary>
        internal static string Sidebar_PromoPrint {
            get {
                return ResourceManager.GetString("Sidebar_PromoPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Special Offers / Sale.
        /// </summary>
        internal static string Sidebar_PromoSale {
            get {
                return ResourceManager.GetString("Sidebar_PromoSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Available Sizes.
        /// </summary>
        internal static string Sidebar_Sizes {
            get {
                return ResourceManager.GetString("Sidebar_Sizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Club / Team.
        /// </summary>
        internal static string Sidebar_Team {
            get {
                return ResourceManager.GetString("Sidebar_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filter Catalog.
        /// </summary>
        internal static string Sidebar_Title {
            get {
                return ResourceManager.GetString("Sidebar_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product Reviews.
        /// </summary>
        internal static string Tab_Reviews {
            get {
                return ResourceManager.GetString("Tab_Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You Might Also Like.
        /// </summary>
        internal static string Tab_Similar {
            get {
                return ResourceManager.GetString("Tab_Similar", resourceCulture);
            }
        }
    }
}
