//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace OFFSIDESHOP
{
    public partial class AdminAudit
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        protected global::System.Web.UI.WebControls.Button btnManageProducts;
        protected global::System.Web.UI.WebControls.Button btnManageOffers;
        protected global::System.Web.UI.WebControls.Button btnManageCoupons;
        protected global::System.Web.UI.WebControls.Button btnAddLeague;
        protected global::System.Web.UI.WebControls.Button btnAddTeam;
        protected global::System.Web.UI.WebControls.Button btnAddBrand;
        protected global::System.Web.UI.WebControls.PlaceHolder phOwnerMenu;
        protected global::System.Web.UI.WebControls.Button btnManageUsers;
        protected global::System.Web.UI.WebControls.Button btnSmtpSettings;
        protected global::System.Web.UI.WebControls.Button btnStats;
        protected global::System.Web.UI.WebControls.Button btnAuditLogs;
        protected global::System.Web.UI.WebControls.Button btnAdminBanners;
        protected global::System.Web.UI.WebControls.Button btncerrar;
        protected global::System.Web.UI.UpdatePanel upAuditLogs;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterAction;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterModule;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.Button btnClear;
        protected global::System.Web.UI.WebControls.GridView gvAuditLogs;
    }
}
